# Generated by Django 3.2.24 on 2024-03-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_subscriber_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
