# Generated by Django 3.2.24 on 2024-03-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_size',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='print_paper',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
