# Generated by Django 3.2.24 on 2024-03-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20240310_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_print',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
